apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  ports:
    - port: 3000
      nodePort: 30001
  selector:
    app: grafana
    tier: frontend
  type: NodePort
