apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  ports:
    - port: 9090
      nodePort: 30002
  selector:
    app: prometheus
    tier: frontend
  type: NodePort
